repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.15.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
